// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvNpuvFkVqSTzsX3JqJEaj3dJdgQIwMhg',
    appId: '1:49185209458:web:07d8fed78fcfa46b0b96eb',
    messagingSenderId: '49185209458',
    projectId: 'fasum-ac663',
    authDomain: 'fasum-ac663.firebaseapp.com',
    databaseURL: 'https://fasum-ac663-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-ac663.appspot.com',
    measurementId: 'G-BCFVRGR4M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh3Zr6PyuTy8_8jlR-rts2XCYzWFsV1EQ',
    appId: '1:49185209458:android:9b52c55ca3b2d92f0b96eb',
    messagingSenderId: '49185209458',
    projectId: 'fasum-ac663',
    databaseURL: 'https://fasum-ac663-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-ac663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4iWl93IxV4v1XYMq8NHQubliP5cabthU',
    appId: '1:49185209458:ios:e598c789a637423b0b96eb',
    messagingSenderId: '49185209458',
    projectId: 'fasum-ac663',
    databaseURL: 'https://fasum-ac663-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-ac663.appspot.com',
    iosBundleId: 'com.example.aplikasiFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4iWl93IxV4v1XYMq8NHQubliP5cabthU',
    appId: '1:49185209458:ios:5ae9282827387bbe0b96eb',
    messagingSenderId: '49185209458',
    projectId: 'fasum-ac663',
    databaseURL: 'https://fasum-ac663-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-ac663.appspot.com',
    iosBundleId: 'com.example.aplikasiFasum.RunnerTests',
  );
}
